# Site
repository: drewmattic/PVP-Resume
favicon: images/favicon.ico

# Personal info
name: Drew Frierson
title: Sr. Technical Product Manager
email: FriersonDrew@gmail.com
website: www.github.com/drewmattic/PVP-Resume

# Social links
twitter_username: DrewFrierson
github_username:  DrewMattic
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: 
linkedin_username: friersondrew
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll

# About Section
# about_title: About Me
# about_profile_image: images/drewmattic_profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, I'm Drew Frierson, a creative & innovative Product and Project Manager, Software Engineer, and Blockchain Tech (DLT) advocate, with a reputation for evangelizing and scaling awesome enterprise cloud products. He specializes in a diverse set of technical & management skills, which includes, but not limited to: Business and Project Development, Technical Product Management, and Cloud Behavioral Engineering.

  Valued and Experience in the Following:
    - <mark>Product Management, experience defining and shipping enterprise cloud infrastructure platform products at scale</mark>
    - <mark>Developing product strategy and managing strategic product roadmaps</mark>
    - <mark>Distributed Ledger Technology</mark>
    - <mark>Strategy/business development</mark>
    - <mark>Effective communication and engaged listening</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Dark Mode (true/false/never)
# darkmode: false

# Build settings
theme: modern-resume-theme
# remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
